---

- fail:
    msg: "variable {{ item }} is not set! "
  when: "{{ item }} is not defined or {{ item }}== ''"
  with_items:
    - tweak_registry_name


- name: template docker service config file
  template:
    src: docker-insecure.j2
    dest: /etc/systemd/system/docker.service.d/docker-insecure.conf


- name: reload systemd
  shell: systemctl daemon-reload


- name: restart service
  service:
    name: docker.service
    enabled: yes
    state: restarted
