apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kcm-discover-pod
  name: kcm-discover-pod
spec:
  containers:
  - args:
    - "/kcm/kcm.py discover --conf-dir=/etc/kcm"
    command:
    - "/bin/bash"
    - "-c"
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    image: kcm:v0.1.0
    name: kcm-discover-pod
    volumeMounts:
    - mountPath: "/etc/kcm"
      name: kcm-conf-dir
  restartPolicy: Never
  volumes:
  - hostPath:
      # Change this to modify the KCM config dir in the host file system.
      path: "/etc/kcm"
    name: kcm-conf-dir
