---

- name: check if kubectl is present in workdir
  stat:
    path: ./kubectl
  failed_when: false
  register: kctl_present

- name: check kubctl version
  shell: ./kubectl version --client | awk '{print $5}'
  register: kubctl_version
  when: kctl_present.stat.exists

- name: Download kubectl
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/{{kube_version}}/bin/linux/amd64/kubectl"
    dest: ./kubectl
    mode: 0775
  when:
   - "not kctl_present.stat.exists or '{{ kube_version }}' not in kubctl_version.stdout"
