---


- name: archive k8s credentials
  shell: tar -zcf k8s_config.tar.gz /etc/kubernetes -P


- name: fetch k8s credentials
  fetch:
    src: ./k8s_config.tar.gz
    dest: ./
    flat: yes
    fail_on_missing: yes


- set_fact:
    api_server_ip: "{{ hostvars[ansible_play_hosts[0]]['ip'] }}"


- block:

  - name: prepare credentials folder
    shell: rm -rf ./credentials && mkdir ./credentials

  - name: unpack k8s credentials
    shell: tar -xf k8s_config.tar.gz -C ./credentials --strip-components=2 -P -m

  - name: remove k8s zip
    shell: rm -rf k8s_config.tar.gz

  - name: template kubectl config
    template:
      src: kubectl_config.j2
      dest: ./config.yml

  delegate_to: localhost
  become: False


